[env:waveshare-cam]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM15
monitor_port = COM15
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -O2
lib_deps =
    moononournation/GFX Library for Arduino@1.5.0
    lewisxhe/XPowersLib@^0.2.6
